import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import localFont from 'next/font/local';

// const inter = Inter({ subsets: ['latin'] });

const segoeUIFont = localFont({
    src: [
        {
            path: './fonts/segoe-ui/Segoe UI.ttf',
            weight: '400',
            style: 'normal'
        },
        {
            path: './fonts/segoe-ui/Segoe UI Italic.ttf',
            weight: '400',
            style: 'italic'
        },
        {
            path: './fonts/segoe-ui/Segoe UI Bold.ttf',
            weight: '700',
            style: 'normal'
        },
        {
            path: './fonts/segoe-ui/Segoe UI Italic.ttf',
            weight: '700',
            style: 'italic'
        }
    ]
});

export const metadata: Metadata = {
    title: 'Gestión de Pedidos de Transporte',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es">
            <head>
                <meta charSet="UTF-8"></meta>
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Gestión de Pedidos de Transporte</title>
            </head>
            <body className='body-con-fondo'>
                {children}
            </body>
        </html>
    );
}
